backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - label: "Categoria"
        name: "tag"
        widget: "select"
        options:
          - "E-commerce"
          - "Comparativo"
          - "Técnico"
          - "Mudança"
          - "Dicas"
      - { label: "Resumo", name: "description", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
